### ISSUE TITLE
Why does Mouf need Apache write access to the vendor folder ?

### ISSUE THREAD

**Issue by stof** [thecodingmachine/mouf#106]
This makes me think that the install UI tries to edit some files in Mouf itself, which looks really weird to me. Why would vendors be modified in the app ? This is the opposite of best practices.

**Comment by moufmouf** [comment]
Internally, Mouf calls Composer functions (by including the `composer.phar` file).

Composer needs to write a cache. By default, the cache goes in the `www-data` home directory. But on many production environment, the `www-data` user has not the right to write in its home directory (most of the time /var/www). So I need to find a place to write this damn cache. At the time, I chose to write it in the `/vendor/mouf/mouf/.composer` dir.

I could definitely work on it but the truth is that the next version of Mouf will not have this problem.
The next version of Mouf will use the PHP web-server, started via the CLI to start a dedicated Mouf web-server. This has a number of advantages:
- The mouf environment can be accessible only in dev environments
- The mouf process will use the current user instead of "www-data", so all those issues will naturally disappear.

I'm marking this issue as "enhancement" and will close it with the future release of Mouf 2.1.

**Comment by stof** [comment]
Why not putting it in a folder in the temp dir instead for now instead of inside the `vendor/mouf/mouf` folder ?
The fact that this cache files were owned by www-data means that `composer install` in Packanalyst failed when deps where updated because composer was unable to delete the old Mouf version.
