### ISSUE TITLE
The config validator should not complain about apc.shm_size when usign PHP 5.5+ with OPCache

### ISSUE THREAD

**Issue by stof** [thecodingmachine/mouf#107]
At least from my understanding, this validation rule does not make sense in this case.

**Comment by moufmouf** [comment]
Actually, it does.
Mouf stores a lot of stuff in APC user land cache (APCu).
In particular, it stores a modified version of all the reflection data about classes and methods.

If the APCu cache size is too low, the cache items will be flushed before being used. This will make the Mouf interface very slow.

So this is indeed needed, even with PHP 5.5 and Opcache, because Opcache does not provide userland cache.

**Comment by stof** [comment]
Ah, `apc.shm_size` affects the user cache too indeed
