### ISSUE TITLE
Unable to make a "foreach" on a newly created TDBM_Object

### ISSUE THREAD

**Issue by WizMik** [thecodingmachine/mouf#75]
When a Bean is created ( $dao->create() ), you can't acess its properties through a foreach (because the bean has no properties unless they've been initiated or loaded from the database).

It could be usefull to initiate Bean's properties of a newly created TDBM_Object with a foreach !

**Comment by moufmouf** [comment]
Indeed. In order to fix this, we would need to:
- When a bean is just created, it has a "new" status
- In this status, the $db_row list of columns is not loaded. If we were to fill it, we would need to access the db model and initiate the row with all default values (some of them can be very hard to fetch if the default db value is a function like "NOW()" for instance)

Basically, it is very difficult to fix. Moreover, it is likely TDBM 4 will not let you access properties directly (or do a foreach on a property) but instead will force you through the setters and getters. So you should probably avoid doing a foreach on an object since this will be deprecated. I'll keep this bug as a "won't fix".
